### ISSUE TITLE
Stats doesn't work properly with CSS variables

### ISSUE THREAD

**Issue by lean8086** [cssstats/cssstats#289] opened 2019-12-17 01:53 UTC
Hi :) It seems like some stats like color declarations, font families and font sizes are not evaluated properly when using CSS variables?

https://cssstats.com/stats?url=lean8086.com

![image](https://user-images.githubusercontent.com/265560/70957800-93239080-2077-11ea-8016-e12a6c4fab65.png)

![image](https://user-images.githubusercontent.com/265560/70957756-72f3d180-2077-11ea-9dfa-bed13af2b252.png)

![image](https://user-images.githubusercontent.com/265560/70957779-80a95700-2077-11ea-83f0-5ed30eab0e7e.png)

**Comment by bartveneman** [comment] 2020-02-14 21:16
Custom properties are evaluated by the browser at 'runtime', meaning that `var(--my-custom-property)` could have different calculated values, based on the place it has in the document, the default/fallback value and probably some other cases I'm not thinking of at the moment.

CSSStats does not know about all this context, because all it analyzes is the raw CSS it encounters on a given page. It would be impossible to render the variables correctly based only on the CSS.

But perhaps there's something I'm missing here? 🤔

**Comment by lachlanjc** [comment] 2020-02-16 23:39
Unfortunately I think ^ is correct. Nonetheless, maybe we could render whatever is defined on :root?

**Comment by lachlanjc** [comment] 2020-12-09 01:22
Closed by #308! @johno

**Comment by johno** [comment] 2020-12-09 19:23
Thanks for bubbling this up @lachlanjc!

The CSS AST has enough information for _most_ custom property handling, though ofc it misses anything affected by a runtime since this tool works purely statically (by design).

v4 now contains a fix that should address 90% or so of variable/custom property usage. It still missed nested variables, but that's something for another day I think so I'm going to close this. Thanks all!

**Closed by johno** 2020-12-09 19:23 UTC
